/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface LoggerInterface extends utils.Interface {
  functions: {
    "log(address,uint256,string)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "log"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "log",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "log", data: BytesLike): Result;

  events: {
    "Log(address,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Log"): EventFragment;
}

export interface LogEventObject {
  caller: string;
  amount: BigNumber;
  action: string;
}
export type LogEvent = TypedEvent<[string, BigNumber, string], LogEventObject>;

export type LogEventFilter = TypedEventFilter<LogEvent>;

export interface Logger extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LoggerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    log(
      _caller: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _action: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  log(
    _caller: PromiseOrValue<string>,
    _amount: PromiseOrValue<BigNumberish>,
    _action: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    log(
      _caller: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _action: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Log(address,uint256,string)"(
      caller?: null,
      amount?: null,
      action?: null
    ): LogEventFilter;
    Log(caller?: null, amount?: null, action?: null): LogEventFilter;
  };

  estimateGas: {
    log(
      _caller: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _action: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    log(
      _caller: PromiseOrValue<string>,
      _amount: PromiseOrValue<BigNumberish>,
      _action: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
