/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bankSol from "./Bank.sol";
export type { bankSol };
import type * as delegatecallSol from "./Delegatecall.sol";
export type { delegatecallSol };
export type { EtherGame } from "./EtherGame";
export type { EtherStore } from "./EtherStore";
export type { FindThisHash } from "./FindThisHash";
export type { GuessTheRandomNumber } from "./GuessTheRandomNumber";
export type { KingOfEther } from "./KingOfEther";
export type { MultiSigWallet } from "./MultiSigWallet";
export type { Roulette } from "./Roulette";
export type { Target } from "./Target";
export type { Theirsverse } from "./Theirsverse";
export type { TimeLock } from "./TimeLock";
export type { Vault } from "./Vault";
export type { Wallet } from "./Wallet";
