/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bankSol from "./Bank.sol";
export type { bankSol };
import type * as delegatecallSol from "./Delegatecall.sol";
export type { delegatecallSol };
export type { EtherGame } from "./EtherGame";
export type { EtherStore } from "./EtherStore";
export type { FindThisHash } from "./FindThisHash";
export type { GuessTheRandomNumber } from "./GuessTheRandomNumber";
export type { KingOfEther } from "./KingOfEther";
export type { MultiSigWallet } from "./MultiSigWallet";
export type { Roulette } from "./Roulette";
export type { Target } from "./Target";
export type { TimeLock } from "./TimeLock";
export type { Vault } from "./Vault";
export type { Wallet } from "./Wallet";
export * as factories from "./factories";
export type { Bank } from "./Bank.sol/Bank";
export { Bank__factory } from "./factories/Bank.sol/Bank__factory";
export type { Logger } from "./Bank.sol/Logger";
export { Logger__factory } from "./factories/Bank.sol/Logger__factory";
export type { HackMe } from "./Delegatecall.sol/HackMe";
export { HackMe__factory } from "./factories/Delegatecall.sol/HackMe__factory";
export type { Lib } from "./Delegatecall.sol/Lib";
export { Lib__factory } from "./factories/Delegatecall.sol/Lib__factory";
export { EtherGame__factory } from "./factories/EtherGame__factory";
export { EtherStore__factory } from "./factories/EtherStore__factory";
export { FindThisHash__factory } from "./factories/FindThisHash__factory";
export { GuessTheRandomNumber__factory } from "./factories/GuessTheRandomNumber__factory";
export { KingOfEther__factory } from "./factories/KingOfEther__factory";
export { MultiSigWallet__factory } from "./factories/MultiSigWallet__factory";
export { Roulette__factory } from "./factories/Roulette__factory";
export { Target__factory } from "./factories/Target__factory";
export { TimeLock__factory } from "./factories/TimeLock__factory";
export { Vault__factory } from "./factories/Vault__factory";
export { Wallet__factory } from "./factories/Wallet__factory";
