/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { EtherGame, EtherGameInterface } from "../../contracts/EtherGame";

const _abi = [
  {
    inputs: [],
    name: "claimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "targetAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "winner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052676124fee993bc000060005534801561001c57600080fd5b506102908061002c6000396000f3fe60806040526004361061003f5760003560e01c8063953b8fb814610044578063b88a802f1461006d578063d0e30db014610084578063dfbf53ae1461008c575b600080fd5b34801561005057600080fd5b5061005a60005481565b6040519081526020015b60405180910390f35b34801561007957600080fd5b506100826100c4565b005b6100826101a2565b34801561009857600080fd5b506001546100ac906001600160a01b031681565b6040516001600160a01b039091168152602001610064565b6001546001600160a01b031633146101105760405162461bcd60e51b815260206004820152600a6024820152692737ba103bb4b73732b960b11b60448201526064015b60405180910390fd5b604051600090339047908381818185875af1925050503d8060008114610152576040519150601f19603f3d011682016040523d82523d6000602084013e610157565b606091505b505090508061019f5760405162461bcd60e51b81526020600482015260146024820152732330b4b632b2103a379039b2b7321022ba3432b960611b6044820152606401610107565b50565b34670de0b6b3a7640000146101f95760405162461bcd60e51b815260206004820152601960248201527f596f752063616e206f6e6c792073656e642031204574686572000000000000006044820152606401610107565b600054479081111561023c5760405162461bcd60e51b815260206004820152600c60248201526b23b0b6b29034b99037bb32b960a11b6044820152606401610107565b600054810361019f57600180546001600160a01b031916331790555056fea2646970667358221220f54f43fb941675a9cc05c1321b8fd031fe85730938678b3d9223bbc8cbffde3064736f6c63430008110033";

type EtherGameConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EtherGameConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EtherGame__factory extends ContractFactory {
  constructor(...args: EtherGameConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<EtherGame> {
    return super.deploy(overrides || {}) as Promise<EtherGame>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EtherGame {
    return super.attach(address) as EtherGame;
  }
  override connect(signer: Signer): EtherGame__factory {
    return super.connect(signer) as EtherGame__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EtherGameInterface {
    return new utils.Interface(_abi) as EtherGameInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EtherGame {
    return new Contract(address, _abi, signerOrProvider) as EtherGame;
  }
}
